# Generated by Django 3.1.4 on 2020-12-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201222_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DoctorID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='NurseID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientID',
            field=models.IntegerField(),
        ),
    ]
